# Generated by Django 5.2.17 on 2026-09-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='accommodation',
            field=models.CharField(default='Alojamiento por confirmar', max_length=150, verbose_name='Alojamiento'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_spots',
            field=models.PositiveIntegerField(default=1, verbose_name='Cupos disponibles'),
        ),
        migrations.AddField(
            model_name='product',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de salida'),
        ),
        migrations.AddField(
            model_name='product',
            name='duration_days',
            field=models.PositiveIntegerField(default=1, verbose_name='Duración (días)'),
        ),
        migrations.AddField(
            model_name='product',
            name='itinerary',
            field=models.TextField(default='Itinerario por confirmar', max_length=1000, verbose_name='Itinerario'),
        ),
        migrations.AddField(
            model_name='product',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de regreso'),
        ),
        migrations.AddField(
            model_name='product',
            name='transport',
            field=models.CharField(default='Transporte por confirmar', max_length=150, verbose_name='Transporte'),
        ),
    ]
